### ISSUE TITLE
Terminal screens gets cut off by footer on Safari

### ISSUE THREAD

**Issue by rkung** [play-with-docker/play-with-docker.github.io#34] opened 2017-03-10 21:07 UTC
The bottom of the terminal screen gets cut off by the footer.  It becomes a problem when trying to type further and can’t see what you are typing, or worried some other information is cut off.  This only happens on Safari.  It doesn’t have the same behavior on Chrome:

**Comment by marcosnils** [comment] 2017-03-11 16:14
@rkung I don't have a mac so I can't reproduce. Would you like to send a PR to fix this and help other safari users?

**Comment by ManoMarks** [comment] 2017-03-13 17:03
I can reproduce in Safari in web-apps tutorial. I don't think Ray will be able to submit a PR. Not sure what is happening, see second image for console results.

<img width="813" alt="screen shot 2017-03-13 at 9 56 24 am" src="https://cloud.githubusercontent.com/assets/113855/23865602/71b0e2aa-07d3-11e7-8955-f36de4f60005.png">

<img width="1043" alt="screen shot 2017-03-13 at 10 02 05 am" src="https://cloud.githubusercontent.com/assets/113855/23865873/4b26e872-07d4-11e7-859a-867ffd25a8d7.png">

**Comment by marcosnils** [comment] 2017-03-13 17:05
@ManoMarks thx for confirming. The javascript error are unrelated. Unfortunately I don't have a Mac to work on this, maybe @xetorthio or someone else can help?

**Comment by ManoMarks** [comment] 2017-03-13 17:09
In that case it should just be a matter of adjusting the CSS, making the height slight smaller. If no one else can, I can look at this later.

**Comment by marcosnils** [comment] 2017-03-13 17:17
> In that case it should just be a matter of adjusting the CSS, making the height slight smaller. If no one else can, I can look at this later.

Thx!. Please verify that at least Chrome looks ok if making changes for safari specific styling issues. We don't want to break what works now :)

**Comment by ManoMarks** [comment] 2017-03-13 17:23
Yeah reluctant to change too much :-)

**Comment by ManoMarks** [comment] 2017-03-13 20:26
There doesn't appear to be a quick and easy fix for this in CSS. I'm not going to be able to do it any time soon. Will get designers working on it.

**Comment by ManoMarks** [comment] 2017-03-14 22:07
I've confirmed this is fixed in #52. Tested in FF,Safari, and Chrome on Mac

**Closed by ManoMarks** 2017-03-14 22:07 UTC
