### ISSUE TITLE
Click here to load website points to page which returns no response

### ISSUE THREAD

**Issue by govindrai** [play-with-docker/play-with-docker.github.io#178] opened 2019-03-24 17:20 UTC
After following tutorials, I expect to see a website running on nginx but I keep getting the following error:
![image](https://user-images.githubusercontent.com/13859249/54883049-42e80c80-4e1e-11e9-917f-628bf648264c.png)

It works on my local machine, so there may be something wrong on PWD side.

**Comment by jlk1980** [comment] 2020-02-03 05:25
Yea same here

**Comment by jxc876** [comment] 2022-08-18 17:41
its due to the port, [the url link in the tutorial](https://training.play-with-docker.com/beginner-linux/#build-a-simple-website-image) is pointed at port `8080`
```
http://ip-xx-x-xxxxxxxxx-8080.direct.labs.play-with-docker.com/
```

but the tutorial actually exposes it on port `80`. 

```
 docker container run \
 --detach \
 --publish 80:80 \ # <<<<<<
 --name linux_tweet_app \
 $DOCKERID/linux_tweet_app:1.0
```

When I fixed the link it started working:

```
http://ip-xx-x-xxxxxxxxx-80.direct.labs.play-with-docker.com/
```

**Comment by marcosnils** [comment] 2022-08-18 18:14
:wave: wanna send a PR to address it? :pray:

**Comment by Privat33r-dev** [comment] 2024-05-02 21:21
Tutorial ports seems to align. I guess it's also a duplicate of #205

**Comment by marcosnils** [comment] 2024-05-02 22:15
Closing as dupe of #205

**Closed as completed by marcosnils** 2024-05-02 22:15 UTC
