### ISSUE TITLE
Windows Containers Basics - unknown blob

### ISSUE THREAD

**Issue by emecas** [play-with-docker/play-with-docker.github.io#44] opened 2017-03-13 22:05 UTC
Lab: windows-containers-basics 

Error:

emecas@G7XGTF2 MINGW64 ~/repos$ docker pull microsoft/windowsservercore:10.0.14393.321
10.0.14393.321: Pulling from microsoft/windowsservercore
9c7f9c7d9bc2: Pulling fs layer
de5064718b3f: Pulling fs layer
9c7f9c7d9bc2: Downloading
de5064718b3f: Downloading
unknown blob

emecas@G7XGTF2 MINGW64 ~/repos$ docker pull microsoft/windowsservercore:10.0.14393.321
10.0.14393.321: Pulling from microsoft/windowsservercore
9c7f9c7d9bc2: Pulling fs layer
de5064718b3f: Pulling fs layer
de5064718b3f: Downloading
unknown blob

**Comment by marcosnils** [comment] 2017-03-13 22:07
@emecas thx for reporting.

dupe of #43

**Closed by marcosnils** 2017-03-13 22:07 UTC
