### ISSUE TITLE
swarm-compose-secrets lab --- not docker for mac compliant

### ISSUE THREAD

**Issue by xxradar** [play-with-docker/play-with-docker.github.io#30] opened 2017-03-10 09:45 UTC
swarm-compose-secrets does not work on Docker for Mac --unsupported flag -i on (some) versions of mac

docker swarm init --advertise-addr $(hostname -i)
does not work

docker swarm init --advertise-addr $(hostname)
does work

Kind regards,

**Comment by xxradar** [comment] 2017-03-10 09:47
Hi

docker swarm init --advertise-addr $(hostname -i) 
does not work

docker swarm init --advertise-addr $(hostname) 
does work

Kind regards,

**Comment by marcosnils** [comment] 2017-03-10 12:55
@xxradar this is weird. Works fine for me

![image](https://cloud.githubusercontent.com/assets/1578458/23796074/a1728a38-0577-11e7-873e-57af95286ac7.png)



Can you attach a screenshot of the error you get?. Also, what does `hostname -i` returns for you?

**Comment by xxradar** [comment] 2017-03-10 14:18
Hi,

I mean if you try the lab on you’re mac (not in the shell of the website)

$ docker swarm init --advertise-addr $(hostname -i)
hostname: illegal option -- i
usage: hostname [-fs] [name-of-host]
flag needs an argument: --advertise-addr
See 'docker swarm init --help'.

**Comment by marcosnils** [comment] 2017-03-11 15:42
Yeah.. the problem is that there's no generic way to make the swarm initialization common to all platforms. The current tutorials are written to work with the online terminal, so it's probable that not all commands work exactly the same on all platforms. 

Not sure of there's something that we could do to improve this.

**Comment by ManoMarks** [comment] 2017-03-13 17:13
Most we can do is note that these labs are designed to run in this terminal or on Linux, some of the bash may need to be altered to run on Docker for Mac or Windows.

**Comment by ManoMarks** [comment] 2017-03-14 22:11
Closing this issue

**Closed by ManoMarks** 2017-03-14 22:11 UTC
